# Minimal declarations for the API used here; tokenizers 0.22.2 ships no
# py.typed marker. Runtime behavior is verified with the real pinned package.
class Encoding:
    @property
    def ids(self) -> list[int]: ...

class Tokenizer:
    @staticmethod
    def from_str(json: str) -> Tokenizer: ...
    def no_truncation(self) -> None: ...
    def no_padding(self) -> None: ...
    def encode(self, sequence: str, add_special_tokens: bool = True) -> Encoding: ...
